"""add route_guide field to services

Revision ID: 26c6d5e5a40c
Revises: c195a6997649
Create Date: 2025-10-25 14:58:34.392891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c6d5e5a40c'
down_revision = 'c195a6997649'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('route_guide', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'route_guide')
    # ### end Alembic commands ###
