"""Initial migration with all models

Revision ID: f570e2316173
Revises: 
Create Date: 2025-10-18 15:54:18.401580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f570e2316173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_document_id'), 'customers', ['document_id'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('airport_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'PAGADA', 'CANCELADA', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('total_cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('popular_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_location_id', sa.Integer(), nullable=False),
    sa.Column('destination_location_id', sa.Integer(), nullable=False),
    sa.Column('sales_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_location_id', 'destination_location_id', name='unique_route')
    )
    op.create_index(op.f('ix_popular_trips_id'), 'popular_trips', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('FLIGHT', 'BUS', 'HOTEL', 'LUGGAGE', 'OTHER', name='servicetype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('event_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_color', sa.String(length=7), nullable=True),
    sa.Column('calendar_icon', sa.String(length=50), nullable=True),
    sa.Column('origin_location_id', sa.Integer(), nullable=True),
    sa.Column('destination_location_id', sa.Integer(), nullable=True),
    sa.Column('pnr_code', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('departure_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_name', sa.String(length=150), nullable=True),
    sa.Column('reservation_number', sa.String(length=50), nullable=True),
    sa.Column('check_in_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('associated_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['associated_service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_order_id'), 'services', ['order_id'], unique=False)
    op.create_table('service_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_images_id'), 'service_images', ['id'], unique=False)
    op.create_index(op.f('ix_service_images_service_id'), 'service_images', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_images_service_id'), table_name='service_images')
    op.drop_index(op.f('ix_service_images_id'), table_name='service_images')
    op.drop_table('service_images')
    op.drop_index(op.f('ix_services_order_id'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_popular_trips_id'), table_name='popular_trips')
    op.drop_table('popular_trips')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_document_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
